### ISSUE TITLE
Invariant Violation within <Element />

### ISSUE THREAD

**Issue by Baransu** [fisshy/react-scroll#185]
I'm using Jest for snapshot testing within my application. Drugin my test:
```js
 it('should match snapshot', () => {
    const tree = renderer.create(<DocumentView {...props} />).toJSON();
    expect(tree).toMatchSnapshot();
  });
```

I'm getting this error because of wrong `findDOMNode` call:

```
Invariant Violation: getNodeFromInstance: Invalid argument.
      
      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at Object.getNodeFromInstance (node_modules/react-dom/lib/ReactDOMComponentTree.js:162:77)
      at Object.findDOMNode (node_modules/react-dom/lib/findDOMNode.js:49:41)
      at Object.registerElems (node_modules/react-scroll/lib/mixins/Helpers.js:228:32)
      at Object.componentDidMount (node_modules/react-scroll/lib/mixins/Helpers.js:217:14)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.it (src/components/__tests__/DocumentView.test.js:74:72)
```

I looked into `Helpers.Element` code and it seems all right so I'm lost right now because I want to send PR with fix if this is error with library itself, but I have no idea what's wrong.

**Comment by Baransu** [comment]
This is error with `react-test-renderer` not supporting `findDOMNode`. They discourage `findDOMNode` in favour of `refs`.

**Comment by Baransu** [comment]
Is there anything agains updating `react-scroll` to JSX and current React conventions?

/cc @fisshy
