### ISSUE TITLE
npm run examples fails

### ISSUE THREAD

**Issue by ktajpuri** [fisshy/react-scroll#298]
npm run examples fails with the following error - 

> webpack-dev-server --config examples/webpack.config.js --no-info --content-base examples

YError: Too many arguments provided. Expected max 2 but received 3.
    at argsert (C:\Users\xxx\Desktop\react-scroll\node_modules\webpack-dev-server\node_modules\yargs\lib\argsert.js:31:13)
    at Object.Yargs.self.alias (C:\Users\xxx\Desktop\react-scroll\node_modules\webpack-dev-server\node_modules\yargs\yargs.js:237:5)
    at module.exports (C:\Users\xxx\Desktop\react-scroll\node_modules\webpack\bin\config-yargs.js:12:4)
    at Object.<anonymous> (C:\Users\xxx\Desktop\react-scroll\node_modules\webpack-dev-server\bin\webpack-dev-server.js:54:36)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
webpack-dev-server 2.10.0
webpack 2.7.0

**Comment by ktajpuri** [comment]
this can be fixed by updating the package.json with below two versions
"webpack": "3.2.0",
"webpack-dev-server": "2.5.0"

**Comment by fisshy** [comment]
Thank you! make a PR! :)
